pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'checkout step'
            }
        }
        stage('Build') {
            steps {
                echo 'build step'
            }
        }
    }

    post {
        success {
            echo 'done'
        }
    }
}
